import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import { QueryProvider } from "@/components/QueryWrapper";
import { SocketProvider } from "@/hooks/SocketContext";
import FeedbackButton from "@/components/FeedbackButton";
import { Toaster as ShadcnToaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AlgoJourney",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased hide-scrollbar`}
        style={{ scrollbarWidth: "none", msOverflowStyle: "none" }}
      >
        <QueryProvider>
          <SessionProviderWrapper>
            <SocketProvider>
              <header className="fixed top-0 left-0 w-full z-50">
                <Navbar />
              </header>
              <main className="w-full flex justify-center min-h-screen relative pt-16 app-scroll">
                {" "}
                {/* Changed from overflow-hidden to relative */}
                <div className="w-full relative">
                  {" "}
                  {/* Added relative positioning */}
                  {children}
                  <Toaster />
                  <ShadcnToaster />
                </div>
              </main>
              <FeedbackButton />
            </SocketProvider>
          </SessionProviderWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
